### PR TITLE
[Merged by Bors] - Fix oops from #26

### PR DESCRIPTION
**Pull request by CleanCut**
I forgot to push the commit with my discord user stuff 🤦🏻‍♂️

### CODE REVIEW

**Review by mockersf — APPROVED** [review]

**Comment by CleanCut** [comment]
Huh, that's weird. What's up with bors?

**Comment by mockersf** [comment]
@cart didn't finish setting it up for this repo 😃

**Comment by cart** [comment]
Sorry should be fixed now :)

**Comment by mockersf** [comment]
> Sorry should be fixed now :)

thanks!

**Pull request closed without merging**
